### 文件目录说明
<hr/>
<table>
<tr>
<td>后台管理</td>
<td>/admin</td>
</tr>
<tr>
<td>网站</td>
<td>/web</td>
</tr>
<tr>
<td>手机网站</td>
<td>/webapp</td>
</tr>
<tr>
<td>苹果客户端</td>
<td>/iosapp</td>
</tr>
<tr>
<td>安卓客户端</td>
<td>/androidapp</td>
</tr>
<tr>
<td>接口</td>
<td>/interface</td>
</tr>
</table>
### 第三方开放平台
<hr/>
[百度开放平台](http://developer.baidu.com)<br/>
[微信开放平台](http://developer.baidu.com)<br/>
[微信公众平台](http://developer.baidu.com)<br/>
[腾讯开放平台](http://developer.baidu.com)<br/>
[新浪开放平台](http://developer.baidu.com)<br/>